a1=input("enter fruit name")
a2=input("enter fruit name")
a3=input("enter fruit name")
a4=input("enter fruit name")
a5=input("enter fruit name")
a6=input("enter fruit name")
a7=input("enter fruit name")
lists=[a1,a2,a3,a4,a5,a6,a7]
print(lists)
fruit=[]
f1=input("enter fruit name")
fruit.append(f1)
f2=input("enter fruit name") 
fruit.append(f2)   
f3=input("enter fruit name")
fruit.append(f3)
f4=input("enter fruit name")
fruit.append(f4)
f5=input("enter fruit name")
fruit.append(f5)
f6=input("enter fruit name")
fruit.append(f6)
f7=input("enter fruit name")
fruit.append(f7)
print(fruit)

