student=[]
s1=int(input("Enter student mark of s1:"))
student.append(s1)
s2=int(input("Enter student mark of s2:"))
student.append(s2)
s3=int(input("Enter student mark of s3:"))
student.append(s3)
s4=int(input("Enter student mark of s4:"))
student.append(s4)
s5=int(input("Enter student mark of s5:"))
student.append(s5)
s6=int(input("Enter student mark of s6:"))
student.append(s6)
s7=int(input("Enter student mark of s7:"))
student.append(s7)
s8=int(input("Enter student mark of s8:"))
student.append(s8)
student.sort()
print(student)

